### ISSUE TITLE
Support tags for service registration

### ISSUE THREAD

**Issue by tgross** [joyent/containerbuddy#10]
Allow the configuration of a service registration to include tags that the discovery backend can expose for consumption by `backend` handlers. (ex. "prod", "dev")

**Comment by tgross** [comment]
@misterbisson this was one of your suggestions from my original notes. Do you have further thoughts on what this looks like?

**Comment by misterbisson** [comment]
I'd leave this one in the icebox for now. Tagging for `dev` or `prod` is discussed in some contexts, but I'd rather isolate those environments in entirely different networks with separate discovery catalogs.

**Comment by tgross** [comment]
Merged in https://github.com/joyent/containerbuddy/pull/59 and will be in the next release (0.0.6).

**Comment by tgross** [comment]
Released in https://github.com/joyent/containerbuddy/releases/tag/0.1.0
