### ISSUE TITLE
Logging failure after 1.1

### ISSUE THREAD

**Issue by tgross** [joyent/containerbuddy#105]
Given the following config file:

```json
{
  "consul": "consul:8500",
  "logging": {
    "level": "DEBUG",
    "format": "default",
    "output": "stderr"
  },
  "services": [
    {
      "name": "myservice",
      "port": 80,
      "poll": 10,
      "ttl": 30
    }
  ]
}
```

we expect the output to be:

```bash
$ ./containerbuddy -config file:///containerbuddy.json hello-world.sh
2016/03/09 19:16:18 `health` is required in service jenkins
```

but instead we get:

```bash
$ ./containerbuddy -config file:///containerbuddy.json hello-world.sh
$ echo $?
1
```

This failure happens after the logging framework is set up in [this section](https://github.com/joyent/containerbuddy/blob/master/containerbuddy/config.go#L248-L253). But if we force the failure to happen before we set up the logging, for example with the config file, we get the same non-logging behavior:

```json
{
  "consul": "consul:8500",
  "etcd": "etcd:4001",
  "logging": {
    "level": "DEBUG",
    "format": "default",
    "output": "stderr"
  },
  "services": [
    {
      "name": "myservice",
      "port": 80,
      "poll": 10,
      "ttl": 30
    }
  ]
}
```

**Comment by tgross** [comment]
As an aside, and we should fix it here, the logging config in the example in the README still says `"format": "go"` instead of `"format": "default"`.

**Comment by tgross** [comment]
Removing the initialization at https://github.com/joyent/containerbuddy/blob/d86863bf62190024fb9c682db65f477020ae3c29/containerbuddy/logging.go#L31 seems to fix this but I'm not sure I understand why yet.

**Comment by tgross** [comment]
It looks to me from the logrus docs that when we're importing logrus via `log "github.com/Sirupsen/logrus"` we're getting Logrus' default logging anyways. PR inbound.

**Comment by tgross** [comment]
> PR inbound.

Nope! Turns out I was totally off-base there. It's our default logger that breaks everything. Works fine if we pass `text` or `json` as the output format. That narrows things quite a bit!

**Comment by tgross** [comment]
I have a minimal failing test case that exercises the broken code:

```go
func TestDefaultFormatter(t *testing.T) {
	formatter := &DefaultLogFormatter{}
	b, err := formatter.Format(log.WithFields(
		log.Fields{
			"level": "info",
			"msg":   "something",
		},
	))
	fmt.Printf("%v\n", err)
	fmt.Println(string(b))
}
```

This test *panics(!)* because it reaches [log.Panicln](https://github.com/joyent/containerbuddy/blob/d86863bf62190024fb9c682db65f477020ae3c29/containerbuddy/logging.go#L84), which we shouldn't be hitting at all!

I'm still working thru this but will pick it up tomorrow morning. @justenwalker any thoughts on this?

**Comment by justenwalker** [comment]
I think the problem is [here](https://github.com/Sirupsen/logrus/blob/74bde9ea4c5b2c78995da8ed56d37e75644dc941/logrus.go#L71)

Essentially, PanicLevel == 0, so any log entry with an un-initialized level is assumed to be Panic

**Comment by justenwalker** [comment]
The real issue is handling Panic and Fatal in the Formatter - it just doesn't make sense and it is also redundant since Logrus does this for us. #106 should fix the bug (and update the README for the "go" format)

**Comment by tgross** [comment]
Thanks for the assist, @justenwalker!

**Comment by tgross** [comment]
I've verified that this fix corrects the problem described at the top of the issue as well.

**Comment by tgross** [comment]
Will release this in 1.2.0 (master has a new config flag from #102) this morning.

**Comment by tgross** [comment]
Released in https://github.com/joyent/containerbuddy/releases/tag/1.2.0
