### ISSUE TITLE
Add an alternate service discovery backend

### ISSUE THREAD

**Issue by tgross** [joyent/containerbuddy#11]
The PR https://github.com/joyent/containerbuddy/pull/4 provided by @bbox-kula made the changes we needed to have a generic interface for service discovery so we can have pluggable backends as intended. Including a second implementation of this backend as an example would make sure this works out in practice.

TODO on this issue: pick a second backend

**Comment by stonevil** [comment]
+1

I'm interesting to add etcd backend support.

**Comment by tenfourty** [comment]
+1 on etcd as the next backend to be supported.

**Comment by tgross** [comment]
@stonevil did you want to take that on?

**Comment by bbox-kula** [comment]
@stonevil I've got some ideas, if you wanted to bounce ideas off of someone. Otherwise, after things settle down here I'd take a crack at adding it.

**Comment by tgross** [comment]
Released in https://github.com/joyent/containerbuddy/releases/tag/0.1.0
