### ISSUE TITLE
Overriding config options from command line

### ISSUE THREAD

**Issue by lguminski** [joyent/containerbuddy#121]
The config file of containerbuddy is typically built in into images. It would be nice to have an option to easily override its settings from command line when starting docker container:

```bash
/bin/containerbuddy -consul $CONSUL_ADDRESS -config file:///etc/containerbuddy.json mysqld --console --log-bin=mysql-bin --log_slave_updates=ON --gtid-mode=ON --enforce-gtid-consistency=ON
```

This way consul's address could be easily specified in runtime.

**Comment by tgross** [comment]
There are a couple different ways to add runtime configuration.

The config file itself can be passed in as an environment variable, ref [configuring-containerbuddy](https://github.com/joyent/containerbuddy#configuring-containerbuddy). An example of that usage can be found in our [`triton-nginx` demo](https://github.com/tgross/triton-nginx/tree/master/example).

An alternate (and I think better) way of doing what you're looking for is to make the Containerbuddy config file [interpolate environment variables](https://github.com/joyent/containerbuddy#template-configuration). This would let you pass in the Consul address like this:

```json
{
  "consul": "{{ .CONSUL_ADDRESS }}",
}
```

**Comment by lguminski** [comment]
It's even better indeed. Thanks.
