### ISSUE TITLE
Advice for handling applications that can't reload config without restarting

### ISSUE THREAD

**Issue by yarmiganosca** [joyent/containerbuddy#126]
Many of the programs we're trying to containerize with containerbuddy can't reload their config "in-process" and instead "reload" via the traditional "kill the old process & spawn a new one" dance. When they go to do this, containerbuddy exits, taking the container with it. I understand that this is currently intended behavior. I think it would be useful to have some limited (but not full-blown) "process supervisor" functionality. At least the ability to tell containerbuddy to start watching a new pid would be completely sufficient for this predicament. That said, I'm aware from the docs that you may just not want to write any kind of process supervision functionality into containerbuddy. If that's the case, and you really believe this kind of thing is out of scope for containerbuddy, what do you recommend with these kinds of programs?

**Comment by micahlmartin** [comment]
+1 for this. I've had to roll my own wrapper script for several projects to manage the process. It's definitely less than ideal. Seems like an easy pattern that could be rolled into containerbuddy.

**Comment by tgross** [comment]
@yarmiganosca you're right in that we've definitely considered this sort of thing out-of-scope. But you're also right that there are some applications that are particularly stubborn about this problem and I've run into it myself without a satisfactory answer. For example: Couchbase spawns a whole bunch of processes and doesn't allow config reload... fortunately it's also self-clustering once you connect a node to the pool of nodes so it didn't come up in practice. I hacked the behavior into Express for https://github.com/autopilotpattern/workshop too.

I'm trying to manage end-user complexity here though, so if taking on a small behavior makes end-user complexity significantly smaller it might be worth looking into having options. @micahlmartin would you care to share one of the scripts you've written? You seem to think it's a simpler problem to solve than I do.

**Comment by micahlmartin** [comment]
@tgross As I wrote the message I knew I would regret saying anything is "easy" =). Here's the script I'm using but I'm sure it probably has a lot of issues I'm missing. The meat of it is in the `start` method

```
#!/bin/bash

if [[ -z ${CONSUL} ]]; then
  fatal "Missing CONSUL environment variable"
  exit 1
fi

generateConfig() {
  debug "Generating config"

  if [ ! -z "$DEBUG" ]; then
    log_level="-log-level debug"
  fi

  confd -onetime -backend env ${log_level}

  debug "----------------- Configuration -----------------"
  debug $(cat /etc/logstash/**.*)
  debug "-----------------------------------------------------"
}

onStart() {
  generateConfig
}

reload() {
  current_config=$(cat /etc/logstash/**.*)

  generateConfig

  new_config=$(cat /etc/logstash/**.*)

  if [ "$current_config" != "$new_config" ]; then
    info "******* Rebooting Logstash *******"
    if [ -f /opt/logstash/pid ]; then
      kill -SIGTERM $(cat /opt/logstash/pid)
    fi
  else
    debug "Configs are identical. No need to reload."
  fi
}

health() {
  nc -z localhost ${SYSLOG_PORT}
}

start() {
  info "Boostrapping..."

  # Logstash doesn't have a hot-reload mechanism until 2.3 comes out.
  # This hackery allows us to restart logstash without killing the container.
  # The `/bin/manage.sh reload` function will kill logstash if it detects new configuration.
  while true; do

    # check if logstash is already running
    pid=$(test -f /opt/logstash/pid && test -d /proc/$(cat /opt/logstash/pid) && cat /opt/logstash/pid)

    # If it's not running then start it
    if [ -z "$pid" ]; then

      info "******* Starting Logstash *******"

      su logstash -m -c "/opt/logstash/bin/logstash -f /etc/logstash" &
      echo $! > /opt/logstash/pid

      debug "PID: $(cat /opt/logstash/pid)"

      exitcode=$?
      if [ $exitcode -gt 0 ]; then
        exit $exitcode
      fi
    fi

    sleep 1s
  done
}

debug() {
  if [ ! -z "$DEBUG" ]; then
    echo "=======> DEBUG: $@"
  fi
}

info() {
  echo "=======> INFO: $@"
}

fatal() {
  echo "=======> FATAL: $@"
}

# do whatever the arg is
$1
```

**Comment by misterbisson** [comment]
I've been thinking on this a bit, and there appear to be a few ways to approach this:

1. Kill the main app and let the Docker daemon (or whatever) restart, then everything can configure itself on the way up as usual
1. Use @micahlmartin's approach, which actually looks pretty straightforward
1. Expand the scope of Containerbuddy to accommodate this usage
1. Push for changes in apps to support config reload ([Logstash did it](https://github.com/elastic/logstash/commit/00995378682e90ff50eb3ed244838e9530997294), [ticket](https://github.com/elastic/logstash/issues/4513#issuecomment-193901030))
1. Not Dockerize these apps ;-)

As I think about this, one of the most important reasons that Containerbuddy is not a process supervisor (and adding a feature to support this would definitely cross that line), is that containers are run by process supervisors, be they the Docker daemon, a Mesos framework like Marathon, rkt containers under systemd, or others. Adding another supervisor layer and making it handle all the edge cases that arise from it is doable, but is it something we ​_should_​ do? (Example of complexity: Containerbuddy passes signals through to the main app and we expect the main app to respond, but how does that work if the main app isn't running at that moment?)

**Comment by yarmiganosca** [comment]
@misterbisson I completely understand the slippery slope that is this functionality, and I really appreciate you providing me 4 alternate approaches to the problem. I think each of them is going to be appropriate to different "types" of applications (#5 for datastores, #1 for workers, etc..), and I'll hold off on #3 for the time being ;) . Thanks a lot! I feel like I've gotten what I wanted from asking the question, and would consider the request for advice "closed"; is that a thing that would be appropriate for me to do in this case, or should I leave that to the containerbuddy team?

**Comment by misterbisson** [comment]
@yarmiganosca, don't pass up the opportunity to containerize datastores! We're pretty excited about what we've done with https://github.com/autopilotpattern/couchbase and https://github.com/autopilotpattern/mysql. There's more narrative about each in https://www.joyent.com/blog/docker-nodejs-nginx-nosql-autopilot and respectively https://www.joyent.com/blog/dbaas-simplicity-no-lock-in, though you've probably already seen those.

I agree, however, that some apps are more amenable to the Docker-style containerization than others. Thanks for asking the question, you've helped draw out some answers and thinking that are valuable.

One of the options I forgot to name in my list above is to use Containerbuddy in conjunction with runit, or some other lightweight process supervisor in cases like this. I haven't tested using Containerbuddy to start runit, which could then start a number of other services, but it seems plausible from here.

I'm glad to hear you've got what you needed from the discussion. I'll close the issue, but I'm sure others will reference this over time.
