### ISSUE TITLE
Override interface for ip discovery

### ISSUE THREAD

**Issue by justenwalker** [joyent/containerbuddy#20]
I'm trying to combine [Weave](http://weave.works/) and containerbuddy to register weave IPs in consul-dns. Unfortunately, discovery uses the first IP that it finds from the list of interfaces - which in my case is usually the docker bridge, not the one I want (weave interface).

I'd like to configure the containerbuddy to use `ethwe` instead directly, because I know my containers will be on the weave network: 

**Example of my container's interfaces on the Weave network**
```
root@aab54fefc215:/# ifconfig
eth0      Link encap:Ethernet  HWaddr 02:42:ac:11:00:02
          inet addr:172.17.0.2  Bcast:0.0.0.0  Mask:255.255.0.0
          inet6 addr: fe80::42:acff:fe11:2/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:8 errors:0 dropped:0 overruns:0 frame:0
          TX packets:8 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:648 (648.0 B)  TX bytes:648 (648.0 B)

ethwe     Link encap:Ethernet  HWaddr ee:71:f3:9b:ed:4a
          inet addr:10.130.16.1  Bcast:0.0.0.0  Mask:255.255.224.0
          inet6 addr: fe80::ec71:f3ff:fe9b:ed4a/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1410  Metric:1
          RX packets:8 errors:0 dropped:0 overruns:0 frame:0
          TX packets:9 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:648 (648.0 B)  TX bytes:690 (690.0 B)

lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)
```

Adding an interface override like `"interface": "ethwe"` may help me get the correct IP:

```
{
  "consul": "consul:8500",
  "services": [
    {
      "name": "nginx",
      "port": 80,
      "interface": "ethwe",
      "health": "/usr/bin/curl --fail -s http://localhost/health.txt",
      "poll": 10,
      "ttl": 25
    }
  ],
  "backends": [ ... ]
}
```

**Comment by tgross** [comment]
> Adding an interface override like "interface": "ethwe" may help me get the correct IP:

I feel like [toggling via the `publicIp` boolean](https://github.com/joyent/containerbuddy/blob/c6c3bd3ecf54cf71c53ae932e1796accf6a063af/src/containerbuddy/config.go#L154-L180) was always a bit of a hack. I wrote that bit with Triton in mind but you're right that improving this would go a long way towards enhancing portability.

Let's replace the `publicIp` configuration option entirely and have the interface selected as you've described here (with a sane default like `eth0`). I'll push up a PR for this later today and flag you on it @justenwalker for your thoughts.

**Comment by justenwalker** [comment]
@tgross  I updated the PR to remove publicIp in place of interface.
