### ISSUE TITLE
Add TravisCI Support

### ISSUE THREAD

**Issue by justenwalker** [joyent/containerbuddy#30]
It would be great if we could get automated builds on TravisCI

Could make reviewing easier, since Travis will update the build status on the PR.

**Comment by misterbisson** [comment]
It's interesting you should ask that ;-) @tgross and I were just discussing it earlier.

**Comment by justenwalker** [comment]
Great minds, yadda yadda.

**Comment by tgross** [comment]
I pushed the badge to the README directly so that we can push a build into Travis and get this kicked off. Once the first build is good I'll close this issue.

**Comment by tgross** [comment]
Interesting... the test for the new signal handler failed: https://travis-ci.org/joyent/containerbuddy/builds/94954762

I'm going to close this ticket because TravisCI integration is working, and I'll open a ticket for the bug. (I think it's a race, which is why it worked before.)
