### ISSUE TITLE
TestMaintenanceSignal is failing

### ISSUE THREAD

**Issue by tgross** [joyent/containerbuddy#32]
Our first build on TravisCI failed https://travis-ci.org/joyent/containerbuddy/builds/94954762
The failing test is one that passed when run locally. I believe there's a race in the signal sending set up or tear-down.

```
=== RUN   TestMaintenanceSignal
2015/12/04 20:13:36 we are paused!
--- FAIL: TestMaintenanceSignal (0.00s)
	signals_test.go:51: Should not be in maintenance mode after receiving second SIGUSR1
=== RUN   TestTerminateSignal
.2015/12/04 20:13:36 Caught SIGTERM
2015/12/04 20:13:36 Deregister service: test-service
--- PASS: TestTerminateSignal (1.00s)
```

I'm looking into it, but I'm going to cc @justenwalker because he's been in this area of the code recently.

**Comment by tgross** [comment]
Yeah, there's definitely still some kind of race in the setup/teardown of the signal handlers. I gave justen bad advice on this. I'll have a PR with a fix shortly.

**Comment by justenwalker** [comment]
I ran it again and it succeeded - so its a race

https://travis-ci.org/justenwalker/containerbuddy/builds/94959813

Is it the order in which sendAndWaitForSignal blocks?

```go
	<-sig
	runtime.Gosched()
```

vs.

```go
	runtime.Gosched()
	<-sig
```

**Comment by tgross** [comment]
With that ordering it fails consistently when I run it locally. I suspect the mental model we're using here is flawed somehow about how signal handlers should be set up.

**Comment by tgross** [comment]
I've got a good workaround and I'm testing it now on a WIP branch... we'll set up the signal handler in a helper and then mark that as such in a global bool in the test module. This way we verify that we've only set it up once; the state should be safe to reuse between the signal tests so long as each test covers different signals.

**Comment by justenwalker** [comment]
I don't know why, but this seems to work:

```go
	runtime.Gosched()
	<-sig
	runtime.Gosched()
	signal.Stop(sig) //May not be needed
```

I added a test that re-runs the test 100 times, and it passes.
```go
func TestMaintenanceSignalRace(t *testing.T) {
	for i := 0; i < 100; i++ {
		TestMaintenanceSignal(t)
	}
}
```

**Comment by tgross** [comment]
The only problem with that is that it might only work on your machine (the test that's failing never failed on my machine before, for example, and it still doesn't). If we remove the need to reset the handlers, we can avoid the question entirely. I've got a PR coming to that effect.

**Comment by justenwalker** [comment]
Figured - thats what I get for [coding by coincidence](https://pragprog.com/the-pragmatic-programmer/extracts/coincidence)

**Comment by tgross** [comment]
Interesting... apparently I'm totally wrong. It worked the first time I pushed up the commit (on a very dirty work-in-progress branch) and then not afterwards: https://travis-ci.org/tgross/containerbuddy/builds/94967601

**Comment by tgross** [comment]
Working on this is a little tricky because I can't force the bug on my machine.

**Comment by tgross** [comment]
@justenwalker I tried what you'd suggested in https://travis-ci.org/tgross/containerbuddy/builds/94972692 and it results in the same kinds of errors on Travis.

I'm going to do some integration testing on this and make sure that the signal handler is actually working as I expect and that this isn't just a test artifact.

**Comment by tgross** [comment]
Ok, so fortunately in an integration test this seems to work as we'd expect. That doesn't eliminate a possible race in the implementation that happens when signals arrive close together, of course. But it does lead me to believe that the problem is in the test rig.

**Comment by tgross** [comment]
Think I got it: https://github.com/joyent/containerbuddy/pull/33

**Comment by tgross** [comment]
@justenwalker I slept on this one a bit and woke up this morning with some new insights. We're making what is probably a classic mistake of trying to force behavior in the test by forcing the test thread to yield or by sleeping.  We're trying to fix a concurrency bug within asynchronous signals, and we can't coerce the signals to be received by the `signal` package synchronously.

https://golang.org/pkg/os/signal/ says:
> Package signal will not block sending to c: the caller must ensure that c has sufficient buffer space to keep up with the expected signal rate. For a channel used for notification of just one signal value, a buffer of size 1 is sufficient.

Note the latter bit. I believe the problem is that we're pushing multiple signals into the channel buffer and don't have room. This is causing the main (test) goroutine to block and so we're not making forward progress on the next step of the test and that's causing the weird timing bugs. I'm going to add capacity on the channel and then rework the test to see if I can expose this behavior.

**Comment by tgross** [comment]
I've opened https://github.com/joyent/containerbuddy/pull/36 with what I believe to be the correct solution to the problem.

**Comment by tgross** [comment]
Fix merged and build is now marked as passing. Thanks for the assist on this, @justenwalker
