### ISSUE TITLE
Polling Bug - exec.Cmd is not reusable

### ISSUE THREAD

**Issue by justenwalker** [joyent/containerbuddy#40]
Unfortunately, I did not do adequate testing for #38 and introduced bug.

Parsing the config yields a Cmd object for all commands. However, health checks and backend change hooks are run more than once. Once run, the Cmd object is effectively dead - cannot be run again.

The result is that we hit the failure case in the executeAndWait function and exit prematurely.

This does not affect the preStop, postStop, and onStart Commands since they are only ever run once.

**Comment by tgross** [comment]
Merged that PR in and thank you. I'm wondering if we should build some kind of integration test into the TravisCI workflow... I think that would have caught this?
