### ISSUE TITLE
Example fails

### ISSUE THREAD

**Issue by donniev** [joyent/containerbuddy#44]
When I try to run the example either locally or on Trident it gets to where it starts writing the template file and never exits. See pastebin http://pastebin.com/GQW5KGE6 It has been running at least 1/2hour.

**Comment by tgross** [comment]
In your pastebin, you got this error message:

> ERROR: host volumes are not supported (f882c5e0-a100-11e5-b014-3d7dddf7163f)

Which I know is a provisioning error that I've seen sometimes on Triton when there's an existing container of that sort that's being recreated rather than started new. So what you've got there is that the Consul container never launched and so it's just waiting to try and find Consul. We should probably update the example so that it fails completely rather than hanging in that case though.

Do you have an example of what it looks like when you ran it locally?

**Comment by tgross** [comment]
@donniev for what it's worth I just did a quick run thru to test this myself:

```
$ ./start.sh
Starting example application
project prefix:      example
docker-compose file: docker-compose.yml
Pulling latest container versions
Pulling consul (progrium/consul:latest)...
latest: Pulling from progrium/consul (req cc056e20-a266-11e5-b6cd-0dc5c3b3d9ed)
...
Digest: sha256:8cc8023462905929df9a79ff67ee435a36848ce7a10f18d6d0faba9306b97274
Status: Image is up to date for progrium/consul:latest
Pulling nginx (0x74696d/containerbuddy-demo-nginx:latest)...
latest: Pulling from 0x74696d/containerbuddy-demo-nginx (req ce401be0-a266-11e5-b6cd-0dc5c3b3d9ed)
...
Digest: sha256:37efaba9ff15cd27c93078c3571d399824adf268cef1f15b2099303eabc9242d
Status: Downloaded newer image for 0x74696d/containerbuddy-demo-nginx:latest
Pulling app (0x74696d/containerbuddy-demo-app:latest)...
latest: Pulling from 0x74696d/containerbuddy-demo-app (req d80d43a0-a266-11e5-b6cd-0dc5c3b3d9ed)
...
Digest: sha256:c1248acf7d3cd7e2a9ae28eba270a4db7989985e24a890f0c9ba9d571b2fcafc
Status: Downloaded newer image for 0x74696d/containerbuddy-demo-app:latest
Starting Consul.
Creating example_consul_1
Writing template values to Consul at 165.225.136.171
true
Opening consul console
Starting application servers and Nginx
example_consul_1 is up-to-date
Creating example_nginx_1
Creating example_app_1
Waiting for Nginx at 165.225.136.133:80 to pick up initial configuration.
.................
Opening web page... the page will reload every 5 seconds with any updates.
Try scaling up the app!
docker-compose -p example scale app=3

$ docker-compose -p example ps
         Name                   Command                   State                    Ports
-------------------------------------------------------------------------------------------------
example_app_1            /opt/containerbuddy/co   Up                       0.0.0.0:8000->8000/tcp
                         ntai ...
example_consul_1         /bin/start -server       Up                       0.0.0.0:53->53/tcp,
                         -bootst ...                                       53/udp, 0.0.0.0:8300->
                                                                           8300/tcp, 0.0.0.0:8301
                                                                           ->8301/tcp, 8301/udp,
                                                                           0.0.0.0:8302->8302/tcp
                                                                           , 8302/udp, 0.0.0.0:84
                                                                           00->8400/tcp, 0.0.0.0:
                                                                           8500->8500/tcp,
                                                                           0.0.0.0:8600->8600/tcp
example_nginx_1          /opt/containerbuddy/co   Up                       443/tcp,
                         ntai ...                                          0.0.0.0:80->80/tcp


```

**Comment by donniev** [comment]
i reran the example locally this morning and it completed successfully. I may have forgotten to change my docker envars yesterday so may have never actually run it locally. This morning I looked at the generated default.conf for nginx using docker exec and everything looks good and agrees with what shows up in the browser so local is good to go.

I reran the joyent version this morning and did not receive the volumes error but it still hung on the writing_templates  http://pastebin.com/9ySWAxcU
I did notice it said Creating... instead of ReCreating

**Comment by tgross** [comment]
Is the container `example_consul_1` running at that point? Can you do a `docker ps` on it?

**Comment by donniev** [comment]
I just noticed that in your exmple it says Writing template values to Consul at 165.225.136.171 and when I run it there is no ip listed. Looking at start.sh It is determining that from the machine name. when I do sdc-listmachines |grep name   there is no example_consul_1  but there is 3ccd5c5260_3ccd5c5260_3ccd5c5260_example_consul_1  and tritonclouldflare_consul_1 so that must be the problem.

**Comment by tgross** [comment]
If you do `docker rm 3ccd5c5260_3ccd5c5260_3ccd5c5260_example_consul_1` that should remove the instance that had the weird "volumes" error I described above.

**Comment by donniev** [comment]
in answer to your question about 1/2 hour ago. I removed all my docker containers at joyent and started fresh. It still hangs at that point. If I kill the script and do docker ps  example_consul_1 is up

**Comment by donniev** [comment]
but list-machines is empty http://pastebin.com/Atk4LfPT

**Comment by donniev** [comment]
The machine does show up in the joyent dashboard

**Comment by donniev** [comment]
Could this be because my SDC_URL is in us-sw-1 and the container is in Triton East 1

**Comment by tgross** [comment]
Yeah, that would be it. Because the `sdc-listmachines` will be querying a different DC for purposes of getting that IP for Consul.

**Comment by donniev** [comment]
ok when I changed the SDC_URL to us-east-1 the problem is solved. Perhaps the example should look for that envar when it creates things and if not found default to east?

**Comment by tgross** [comment]
The *Running the example* section of the README includes the setup already. I would not recommend falling back to a default DC just because it could result in unnoticed billing and because it's actually the wrong behavior when running against Docker locally. I'm going to add a remark to the README though so that we ask the user to verify this.

**Comment by donniev** [comment]
If you run the setup commands in the README.md this sets up the DOCKER envars but does not alter the SDC envars which is what listmachines uses so if when you setup the sdc variables and chose a cloud endpoint other than east-1  the examples will fail. I chose the sw endpoint when I installed because I live in Colorado and it seems to make more sense than east. I think a note in the README that you must set SDC_URL to east would help. It still bothers me though that the start script cannot pick up the value.

**Comment by donniev** [comment]
Actually if your example is going to build the containers on east-1 and ignore SDC_URL then rather than have user change SDC_URL if you just add  --url https://us-east-1.api.joyentcloud.com in the list-machine calls  (one for nginx and one for consul) in start.sh the examples will work correctly. I don't like to hard-code context but since your example does it makes sense in this case.

**Comment by tgross** [comment]
It really just assumes that the SDC_URL and DOCKER_HOST match, whichever they are. But that points out the unfortunate situation where the SDC tools can't use the `DOCKER_HOST` for their endpoint because they're different hosts and different APIs. I use something like [this](https://github.com/tgross/how-i-work-when-i-work-with-docker/blob/master/funcs.sh) that gets sourced into my working environment so that I make sure the URLs all match, but admittedly that's a hack and certainly something that should be documented properly rather than assumed.

**Comment by donniev** [comment]
Yeah I am going to set up something like that too. Probably just steal yours as a starting point 😳

**Comment by tgross** [comment]
Opened https://github.com/joyent/containerbuddy/pull/47 to clarify the environment variables situation a bit.

**Comment by tgross** [comment]
Merged in. Going to close this. Thanks for taking the time to walk me thru the issue @donniev

**Comment by donniev** [comment]
No problem. Just ran with new instructions and works perfectly. Hopefully we saved the next guy a few cycles.
