### ISSUE TITLE
Support selecting service IP matching CIDR

### ISSUE THREAD

**Issue by justenwalker** [joyent/containerbuddy#53]
If Triton allows multiple IPs per address (@bahamat on #50), and we potentially have IPV6 (#52) Then perhaps we need to allow services to select their IP in a more flexible way.

Propose something like:

```json
{
  "cidr": "192.168.0.0/16"
}
```

instead of (or in addition to) the `"interfaces"` option

Proposed behavior:
1. Both not given - pick the *first IP* on eth0 (sane default) - *Already Supported*
2. `interfaces` given - pick the *first IP* on the first found interface listed in `interfaces` - *Already Supported*
3. `cidr` given - pick the *first IP* address on any interface matching the CIDR
4. Both given - pick the *first IP* address on any interface (limited to `interfaces`) matching the CIDR

*Note*: *first IP* could be IPV4 or IPV6 - Maybe that's a flag or environment variable that dictates which one is preferred? Depends on what is decided in #52 I suppose. In the `cidr` case, it will always be determined by the whatever version of CIDR is given, so this disambiguation logic applies to 1 and 2

Also, case 4 may be unnecessary if each interface will only have at most 1 v4 and 1 v6 address. In this case it should probably be a parse error instead of handling it specially.

**Comment by bahamat** [comment]
I did say "*Triton* supports", however that's inaccurate (I've edited my comment in #50 to reflect this). SmartOS allows for multiple addresses. This isn't exposed in Triton (JPC) yet.

However, IPv6 is upon us. Recent changes in SmartOS and SDC are leading up to making IPv6 work across the entire stack. When it's available, there may be multiple addresses on any one interface. Most likely in Triton/JPC there will be one IPv4 and one IPv6 address per `nic` object.

**Comment by justenwalker** [comment]
If it's only 1 IPv4 and 1 IPv6 per interface, then probably case 4 is unnecessary.

**Comment by bahamat** [comment]
My comments above are limited to JPC only. On-prem SDC are unrestricted as to how many IPs can be on a single interface.

**Comment by tgross** [comment]
> On-prem SDC are unrestricted as to how many IPs can be on a single interface.

And we're not limiting ourselves to Triton in any case, so who knows what someone is going to want to deploy on.

@justenwalker I like the overall approach here but I'm concerned that this is going to lead to an explosion of options at that level of the JSON hierarchy. What about expanding `interfaces` to take an array of options using the same criteria you've got above? I'd also suggest that we add the option for an index so that folks who know that they always want "the second IP on eth0" can do that. The parsing gets a bit more complicated but the end-user experience is a bit less crazy in the common case:

```json
{
  "interfaces": [
    "eth0", "eth1[1]", "192.168.0.0/16", "2001:db8::/64"
  ]
}
```

Hm... not to open a bikeshedding discussion but how do we feel about that indexing syntax? It's legible but "stringly typed." Maybe we could provide the option to have an associative array to index instead?

```json
{
  "interfaces": [
    "eth0",
    {"eth1": 1},
    "192.168.0.0/16",
    "2001:db8::/64"
  ]
}
```

**Comment by bahamat** [comment]
Like this:

````
{
  "interfaces": [
    "eth0",
    "eth1:1",
    "192.168.0.0/16",
    "2001:db8::/64",
    "inet",
    "inet6",
    "eth2": [ "inet", "inet6" ]
  ]
}
````

Anything else will be confusing to the user.

I also added `inet` and `inet6` as an example of specifying all addresses on all interfaces in v4-only and v6-only respectively, as well as a proposal for all addresses of a specific address family on a specific interface.

**Comment by tgross** [comment]
I'm cool with that syntax.

**Comment by justenwalker** [comment]
What would the behavior of inet and inet6 be exactly?  For instance, would inet be the first ipv4 address it finds in the list of interfaces? 

Also,  I'm not sure about order these interfaces will be coming back, so having something that is _first_ might be ambiguous - Would we impose ordering on the search space to guarantee consistency?

- order interfaces alphabetically
- order ip addresses numerically preferring ipv4 first?

**Comment by bahamat** [comment]
`inet` and `inet6` would be all v4 or all v6 addresses.

**Comment by tgross** [comment]
> all v4 or all v6 addresses

We only advertise one address for each service (the discovery service semantics require that), so what @justenwalker is asking is if we're saying to Containerbuddy "pick one of the ipv4 addresses on that interface" we still need a way to stable-sort those addresses to select one.

> Would we impose ordering on the search space to guarantee consistency?

The API that we're hitting to get this info doesn't make any guarantees of the order, so yeah we should pick something to sort by. Alphabetically then numerically seems a fine way to do it if it's not being defined by the user more explicitly.

**Comment by justenwalker** [comment]
```json
    "eth2": [ "inet", "inet6" ]
``

Is not valid JSON in the context of an array.

How about something like this instead.

```json
{
    "interfaces": [
        "eth0",
        "eth1[1]",
        "192.168.0.0/16",
        "2001:db8::/64",
        "inet",
        "inet6",
        "eth2:inet",
        "eth2:inet6"
    ]
}
```

After a stable sort of interfaces and addresses, the priority of the IP address selected would be determined by the first one that succeeds in this list of steps:

1. Search for eth0 and take the first address
2. Search for eth1 and take the second address (index 1)
3. Search all interfaces and take the one one matching CIDR `192.168.0.0/16`
4. Search all interfaces and take the first one matching CIDR `2001:db8::/64`
5. Search all interfaces and take the first IPv4 Address
6. Search all interfaces and take the first IPv6 Address
7. Search for eth2 and take the first IPv4 address
8. Search for eth2 and take the first IPv6 address

**Comment by justenwalker** [comment]
Also, I'm thinking of making it so that `inet` and `inet6` **never** match the loopback address.  If you want it, you have to put "lo" or "127.0.0.1/8" or something.  Otherwise, if you only specify `inet` and `lo` happens to be ordered first in the list of interfaces, then you'll never get a valid IP.

**Comment by tgross** [comment]
Released in https://github.com/joyent/containerbuddy/releases/tag/0.1.0
