### ISSUE TITLE
1.0?

### ISSUE THREAD

**Issue by tgross** [joyent/containerbuddy#63]
An open item for discussion: what do we need to do yet to get Containerbuddy into what we'll call a 1.0 release?

*Edited list, 2016 Jan 15:*

Will be included:
- [x] Integration test suite:  https://github.com/joyent/containerbuddy/issues/67 https://github.com/joyent/containerbuddy/issues/42
- [x] Fix freeze on reload: https://github.com/joyent/containerbuddy/issues/73
- [x] Reap children: https://github.com/joyent/containerbuddy/issues/62

Will not be included:
- full IPv6 support
- KPIs: https://github.com/joyent/containerbuddy/issues/27

**Comment by misterbisson** [comment]
Great question. Just my 2 cents, but I'd mark the current version as a release candidate and formally tag it when we're comfortable with the tests, including integration tests. I'd hold any new features for post 1.0, including formal IPv6 support, child reaping, KPIs, or others.

**Comment by tgross** [comment]
I'm going to cut a 0.1.0-RC release with the recently-merged etcd and interface spec PRs from @justenwalker and then start marking the remaining issues as either "for 1.0" or "for after 1.0".

**Comment by tgross** [comment]
RC is shipped: https://github.com/joyent/containerbuddy/releases/tag/0.1.0

**Comment by tgross** [comment]
I think based on the discussion w/ @justenwalker in https://github.com/joyent/containerbuddy/issues/62 that I'm going to pull in child-reaping into the 1.0 release as well. The development should be pretty minimal.

**Comment by tgross** [comment]
I've updated the list above. If we can get a last LGTM on https://github.com/joyent/containerbuddy/pull/71 and https://github.com/joyent/containerbuddy/pull/70 then I think we're good-to-go on a release of 1.0.

**Comment by tgross** [comment]
With #71 getting merged in finally, I'm going to cut a second release candidate build just to give us a chance to do some burn-in testing on other applications to make sure we haven't missed anything. But if that's all good we'll release it as 1.0.

**Comment by tgross** [comment]
Unless there are any objections I'm going to cut the final 1.0 release tomorrow morning.

I'll be presenting the work at Golang DC and Golang Philly in the next couple weeks and hopefully recruiting some additional hands from the community in the process!

Big thanks to @justenwalker @bbox-kula and @dobbs for their contributions from the community!

**Comment by misterbisson** [comment]
:+1:

**Comment by justenwalker** [comment]
🎆Yay! 🎆

**Comment by tgross** [comment]
https://github.com/joyent/containerbuddy/releases/tag/1.0.0 has been made live!
