### ISSUE TITLE
Wrong order of DOCKERMAKE mounts

### ISSUE THREAD

**Issue by justenwalker** [joyent/containerbuddy#66]
I think this came up after merging #64 and #61 - one of them overwrites the order in which the volumes are mounted, so .godeps overwrites /src/containerbuddy

**Comment by tgross** [comment]
Right, but when I run the build, I end up with:

```
.godeps/
  |_ containerbuddy/
      |_ <empty>
  |_ github.com/
      |_ hashicorp/
src/
  |_ containerbuddy
      |_ <go code>
```

Is that not what you're seeing?

**Comment by justenwalker** [comment]
I think I had a dirty workspace.  PEBKAC
