### ISSUE TITLE
Add License Badge to README

### ISSUE THREAD

**Issue by justenwalker** [joyent/containerbuddy#68]
One like this - Linked to the LICENSE file

[![MPL licensed](https://img.shields.io/badge/license-MPL_2.0-blue.svg)](https://github.com/joyent/containerbuddy/blob/master/LICENSE)

```markdown
[![MPL licensed](https://img.shields.io/badge/license-MPL_2.0-blue.svg)](https://github.com/joyent/containerbuddy/blob/master/LICENSE)
```

**Comment by misterbisson** [comment]
Nice. Please PR (or include it with another PR) as is convenient.

**Comment by tgross** [comment]
Merged!
