### ISSUE TITLE
CONSUL_HTTP_TOKEN doesn't seem to be supported?

### ISSUE THREAD

**Issue by wleese** [joyent/containerbuddy#78]
I can't seem to get containerbuddy to use CONSUL_HTTP_TOKEN. Logging from the agent:

`Feb 11 14:07:12 host consul[18926]: agent: Synced service 'mesos-consul:xxxxxxxx:tst-logredis:31398'

Feb 11 14:08:41 host consul: 2016/02/11 14:08:41 [ERR] http: Request PUT /v1/agent/check/pass/containername-81eb092d0568?note=ok, error: CheckID does not have associated TTL from=172.17.0.3:55587

Feb 11 14:08:41 host consul[18926]: http: Request PUT /v1/agent/check/pass/containername-81eb092d0568?note=ok, error: CheckID does not have associated TTL from=172.17.0.3:55587

Feb 11 14:08:41 host consul: 2016/02/11 14:08:41 [WARN] agent: Service 'containername-81eb092d0568' registration blocked by ACLs

Feb 11 14:08:41 host consul[18926]: agent: Service 'containername-81eb092d0568' registration blocked by ACLs

Feb 11 14:08:41 host consul: 2016/02/11 14:08:41 [WARN] agent: Check 'containername-81eb092d0568' registration blocked by ACLs

Feb 11 14:08:41 host consul[18926]: agent: Check 'containername-81eb092d0568' registration blocked by ACLs

Feb 11 14:08:51 host consul: 2016/02/11 14:08:51 [WARN] agent: Check 'containername-81eb092d0568' registration blocked by ACLs

Feb 11 14:08:51 host consul[18926]: agent: Check 'containername-81eb092d0568' registration blocked by ACLs

Feb 11 14:08:53 host consul: 2016/02/11 14:08:53 [WARN] agent: Check 'containername-649ba536bd72' missed TTL, is now critical

Feb 11 14:08:53 host consul[18926]: agent: Check 'containername-649ba536bd72' missed TTL, is now critical

Feb 11 14:08:53 host consul[18926]: agent: Check 'containername-649ba536bd72' registration blocked by ACLs

Feb 11 14:08:53 host consul: 2016/02/11 14:08:53 [WARN] agent: Check 'containername-649ba536bd72' registration blocked by ACLs`

Am I correct in believing this is simply not supported at the moment? I've tried the 0.1.1 release and building off of master

**Comment by tgross** [comment]
> Am I correct in believing this is simply not supported at the moment? I've tried the 0.1.1 release and building off of master

That looks to be correct, and this should be considered a bug. It looks like we need to pull in `CONSUL_HTTP_TOKEN` when we set up the [Consul config struct](https://godoc.org/github.com/hashicorp/consul/api#Config), which we do [here](https://github.com/joyent/containerbuddy/blob/76b602efc2738383cc479408cf36073a50274bde/src/containerbuddy/consul.go#L15-L22).

A patch for this would be welcome, otherwise I'll be sure to hit it within the next couple days.

**Comment by wleese** [comment]
Golang isn't my thing, but you asked for it ;)

**Comment by tgross** [comment]
Merged and thanks for the patch, @wleese !

**Comment by tgross** [comment]
Released in https://github.com/joyent/containerbuddy/releases/tag/0.1.2

**Comment by wleese** [comment]
Thanks!
>
>
