### ISSUE TITLE
Error while getting nginx port

### ISSUE THREAD

**Issue by mjgsilva** [joyent/containerbuddy#8]
Hey,

I'm getting an error related to [Nginx port](https://github.com/tgross/containerbuddy/blob/master/examples/start.sh#L57) when running the example locally.

I did some digging and this command does not work.
```
NGINX_PORT=$(docker inspect example_nginx_1 | json -a NetworkSettings.Ports."80/tcp".0.HostPort)
```

Error produced: 
```
command not found: json
write /dev/stdout: broken pipe
```

So I suggest to use the command above instead. Tested and working. 
[Docker docs -> Find a Specific Port Mapping](http://docs.docker.com/engine/reference/commandline/inspect/)

```
NGINX_PORT=$(docker inspect --format='{{(index (index .NetworkSettings.Ports "80/tcp") 0).HostPort}}' ${PREFIX}_nginx_1)
```

I can submit a PR if necessary, just let me know :)

**Comment by tgross** [comment]
@mjgsilva installing the `json` command-line tool is noted in the documentation:

> Install the Docker Toolbox (including docker and docker-compose) on your laptop or other environment, as well as the Joyent CloudAPI CLI tools (including the smartdc and json tools)

That being said, I like that you've got a workaround without it, so I'll make this update.

**Comment by tgross** [comment]
@mjgsilva my commit landed in https://github.com/joyent/containerbuddy/pull/5 because it was against master (arguably I should have done a feature branch but this is pretty minor).

I should note that this only eliminates the use of the `json` command line tool when running against local Docker installation. When running on Triton you'll need the `sdc-listmachines` command and that doesn't support the golang-style formatting directives (it's not a Go program) so need something to parse the JSON.

**Comment by mjgsilva** [comment]
Oh, my bad, I did not install Joyent CloudAPI tools because I though it was only necessary for Joyent services. 

Anyway, if CloudAPI tools are not mandatory to run this locally I suggest this validation. 

´´´
# get Nginx hostport
if [ -z "${COMPOSE_CFG}" ]; then
    NGINX_PORT=$(docker inspect ${PREFIX}_nginx_1 | json -a NetworkSettings.Ports."80/tcp".0.HostPort)
else
    NGINX_PORT=$(docker inspect --format='{{(index (index .NetworkSettings.Ports "80/tcp") 0).HostPort}}' ${PREFIX}_nginx_1)
fi
´´´

**Comment by tgross** [comment]
@mjgsilva I just checked and the `docker inspect --format` works for either case, so to reduce LOC I've only used that.

**Comment by mjgsilva** [comment]
I though it would not work w/ sdc-listmachines cmd. 
You can close this issue now, well done!

**Comment by tgross** [comment]
Thanks for the report, @mjgsilva
