### ISSUE TITLE
Implement log levels

### ISSUE THREAD

**Issue by tgross** [joyent/containerbuddy#88]
Containerbuddy is a bit chatty. Health checks in particular pile up in the Docker logs. Adding (and documenting) log levels wouldn't be a bad idea. A couple options:

- https://github.com/Sirupsen/logrus is used by Docker
- I've also used https://github.com/op/go-logging in other projects

**Comment by justenwalker** [comment]
My vote is for Logrus - i've used it in a couple of internal projects and it seems to be well-used among other golang projects i've seen.

Another thing that would be helpful for logging regardless of the framework: always log Containerbuddy stuff to STDERR to keep it distinct from any application-level logs.

**Comment by tgross** [comment]
> My vote is for Logrus

Ok, let's do it!

> Another thing that would be helpful for logging regardless of the framework: always log Containerbuddy stuff to STDERR to keep it distinct from any application-level logs.

Does this change anything unexpected in the behavior of the Docker log drivers?

**Comment by justenwalker** [comment]
> Does this change anything unexpected in the behavior of the Docker log drivers?
I don't believe so, but I only use `json-file`. I'm unsure about [other log drivers](https://docs.docker.com/engine/admin/logging/overview/). My assumption is that most of them just collapse both streams into whatever protocol they are supporting - perhaps marking each line as coming from stderr or stdout.

**Comment by tgross** [comment]
Ok. For configuring it in the Containerbuddy config, what do we think about doing an associative array as a top-level attribute so that it's easier to add fields later in a backwards-compatible way if we've forgotten something?

```json
{
  "consul": "consul:8500",
  "logging": { "level": "INFO" }
}
```

Another question is whether we treat the addition of a log-level configuration option as a backwards-compatible change (i.e. minor version bump) or consider the change in the log format to be a non-backwards compatible  change (i.e. major version bump). I'm ok with not being a super-stickler over something like log formats, but we should decide deliberately.

**Comment by justenwalker** [comment]
> For configuring it in the Containerbuddy config, what do we think about doing an associative array

Sounds like a good idea

> Another question is whether we treat the addition of a log-level configuration option as a backwards-compatible change (i.e. minor version bump) or consider the change in the log format to be a non-backwards compatible change (i.e. major version bump)

This is probably more critical for libraries than for applications - but my gut says its a Minor version update since its an added feature that shouldn't be backwards incompatible, except perhaps in the [XKCD](https://xkcd.com/1172/) sense.

**Comment by justenwalker** [comment]
You can assign this to me, I should be able to get a first draft in the next day or two.

**Comment by tgross** [comment]
Sounds good.

**Comment by tgross** [comment]
Hm, apparently I can't assign the issue to you in the GitHub interface. I'll have to circle back with the admin of the repo to see whether that can be adjusted. In the meantime, you've licked this cookie. :grinning:

**Comment by justenwalker** [comment]
:yum:  :cookie:

**Comment by tgross** [comment]
This has been merged and is awaiting release. I'd like to get the two open PRs #94 and #95 merged in and then release what I believe we should calling 1.1.0 for this backwards-compatible change.

**Comment by tgross** [comment]
Released in https://github.com/joyent/containerbuddy/releases/tag/1.1.0. Thanks @justenwalker!
