### ISSUE TITLE
Consul: Figure out why Consul is registering a Server node rather than the Client node when using Agent API

### ISSUE THREAD

**Issue by justenwalker** [joyent/containerbuddy#89]
Update:  I thought this was due to using the Catalog API rather than the Agent API but we are already using the Agent API.  Needs a bit more investigation - perhaps my expectations are wrong.

The service definition that I get is:

```json
{
    "Node": "consul-server1",
    "Address": "10.111.0.1",
    "ServiceID": "my-service-8d462d139c39",
    "ServiceName": "my-service",
    "ServiceTags": [],
    "ServiceAddress": "10.222.0.100",
    "ServicePort": 3000,
    "ServiceEnableTagOverride": false,
    "CreateIndex": 2403,
    "ModifyIndex": 2409
},
```

What I expect to get is:

```json
{
    "Node": "consul-agent1",
    "Address": "10.222.1.100",
    "ServiceID": "my-service-8d462d139c39",
    "ServiceName": "my-service",
    "ServiceTags": [],
    "ServiceAddress": "10.222.0.100",
    "ServicePort": 3000,
    "ServiceEnableTagOverride": false,
    "CreateIndex": 2403,
    "ModifyIndex": 2409
},
```

**Comment by tgross** [comment]
Are you running against a non-server Consul node? I thought (and I could be wrong) that this is what you'd expect to see if all the Consul nodes were running as servers and not clients.

**Comment by justenwalker** [comment]
Yes, the local agent is in 'client' mode and not 'server' mode - but I'm not sure how the node information would be useful if it the client agent just registered whichever server node it reached rather than supplying its own IP as the node addresse.

**Comment by tgross** [comment]
It's my understanding that Consul client nodes don't participate in the raft. In which case, only the server node reached is important to Consul because that's how it's going to determine whether the write succeeds (i.e. that the server has a quorum for the write). The clients are just forwarders.

**Comment by justenwalker** [comment]
Ah, then my misunderstanding. I'll close this.
