### ISSUE TITLE
Support configuration reload

### ISSUE THREAD

**Issue by tgross** [joyent/containerbuddy#9]
Accept a signal to reload the Containerbuddy configuration file on external changes. Implementation details:

- The [os/signal](https://golang.org/pkg/os/signal/) package provides the mechanism to accept POSIX signals.
- The signal can reload the configuration by re-parsing the configuration at [parseConfig](https://github.com/joyent/containerbuddy/blob/5877d360fc228f0586ea9dfeda8a12ee60b03c35/src/containerbuddy/config.go#L105)
- We already have a `quit` channel for each of the goroutines running `checkHealth` or `checkForChange`, so the easiest way to reload the configuration would be to send the quit signal to all these goroutines and recreate them with the new config.
- We can't update the environment variables of a running process, so this option will not be open in that scenario.

cc @misterbisson

**Comment by misterbisson** [comment]
> We can't update the environment variables of a running process, so this option will not be open in that scenario

Worth highlighting https://github.com/joyent/containerbuddy/issues/16 in that context. Obviously it can't be fixed, but we'll want to document it.

**Comment by tgross** [comment]
Also ref https://github.com/joyent/containerbuddy/issues/17 for my concerns about using up our available signals.

**Comment by tgross** [comment]
From a design standpoint it's important to note that the `onStart` handler can't be safely re-triggered and that we can't modify the running application.

**Comment by tgross** [comment]
Per our sidebar discussion I'm going to work on implementing this next.

**Comment by misterbisson** [comment]
So, `SIGHUP` will trigger a reload of the config, but your points in https://github.com/joyent/containerbuddy/issues/9#issuecomment-164449096 about re-triggering `onStart` and modifying the running app are good ones. 

We'll want to be very clear which use-cases work well for this and which ones should be addressed by restarting the container or starting a new container.

**Comment by tgross** [comment]
Merged in. Released in https://github.com/joyent/containerbuddy/releases/tag/0.0.5
