### ISSUE TITLE
etcd config does not accept list of endpoints

### ISSUE THREAD

**Issue by tgross** [joyent/containerbuddy#92]
Ran into this while working on https://github.com/joyent/containerbuddy/issues/91. The etcd configuration is supposed to accept a list of endpoints as documented in the README:

```json
{
  "etcd": {
    "endpoints": ["http://etcd1:4001"]
  }
}
```

But this throws the error `Must provide etcd endpoints`, which comes from [here where we switch over the config values](https://github.com/joyent/containerbuddy/blob/e392ab6b627f032822c80c88f40b9fc20b737121/containerbuddy/etcd.go#L43). Passing single string for a single host works fine. [This section of our etcd tests](https://github.com/joyent/containerbuddy/blob/e392ab6b627f032822c80c88f40b9fc20b737121/containerbuddy/etcd_test.go#L9-L11) also works, which suggests that the problem is in the configuration file parsing and not the switch where we're throwing the error.

**Comment by justenwalker** [comment]
@tgross Does that config you gave reproduce the error?

How about this one:

```json
{
  "etcd": {
    "endpoints": ["http://etcd1:4001"]
  },
  "services": [
    {
        "name": "serviceA",
        "port": 8080,
        "interfaces": "eth0",
        "health": "/bin/to/healthcheck/for/service/A.sh",
        "poll": 30,
        "ttl": 19,
        "tags": ["tag1","tag2"]
    }
  ]
}
```

**Comment by tgross** [comment]
That config was abbreviated for purposes of illustration. The one I was actually using was https://github.com/joyent/containerbuddy/blob/master/integration_tests/fixtures/nginx/etc/nginx-with-etcd.json but with brackets like `"endpoints": ["http://etcd:4001"],`

I haven't dug into this past "hm that's an odd error to be getting"

**Comment by justenwalker** [comment]
I think I know now why it does this. The type is `[]interface{}` instead of `[]string`
